### ISSUE TITLE
Fixer petit bug sur search bar.

### ISSUE THREAD

**Issue by luctst** [luctst/pokedex#5]
**Describe the bug:**
*@Kvin3324 Du coup j'ai pas mal avancé sur les filtres tu pourras aller checker le code j'ai documenté une partie pas eux le temps de tout faire mais à part ça tout fonctionne en grande partie. Jusqu'à présent j'ai trouver qu'un petit bug je te le décris plus bas.*

**To Reproduce:**
1. Quand l'appli est lancée.
2. Commence à écrire dans la search bar. (ex: blastoise)
3. La liste devrait s'update.
4. Rajoute maintenant des filtres. (ex: Water)
5. La liste s'update mais sans que la nom soit prit en compte.

**Expected behavior**
Les filtres devrait également prendre en compte le nom lorsqu'on les modifie.

**Additional information's**
Alors à l'inverse le bug se passe seulement quand tu cherches un nom sans avoir modifié les filtres, par contre si tu changes les filtres et que la tu entres un nom tout se passe bien.

**Comment by Kvin3324** [comment]
@luctst Merci de ton retour, j'ai vu les problèmes, j'ai peut-être trouvé une solution aux filters qui prennent bien en compte le nom recherché mais c'est à confirmer mais il y a d'autres soucis face à cela 

1. Si on rentre un nom et on applique des filters c'est good mais si on change le nom, c'est l'ancien qui est gardé.
2. Si on applique un autre filter (ex: Hp or Supertype), il s'applique en tant que valeur au dernier filter appliqué (ex: rarity=hp)
3. L'url se update mais pas avec la valeur du filter "name"
